name: CI

on:
  push:
    branches:
      - master

jobs: 
  lint: 
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v3
      - name: Run GolangCI-Lint Action by building from repository
        uses: matoous/golangci-lint-action@v1.1.0