name: CI

on:
  push:
    branches:
      - master

jobs: 
  lint: 
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
        uses: golangci/golangci-lint-action@v3.2.0