name: CI

on:
  push:
    branches:
      - master

jobs: 
  lint: 
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v3
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1.1.0